# Generated by Django 6.0.5 on 2026-05-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-trophy', max_length=50)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/achievements/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('clinic', 'Clinic & Facility'), ('before_after', 'Before & After'), ('events', 'Events & Camp'), ('team', 'Team & Doctors'), ('patients', 'Happy Patients'), ('equipment', 'Equipment & Technology')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-images', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='gallery/before_after/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='gallery/before_after/')),
                ('is_before_after', models.BooleanField(default=False)),
                ('service_type', models.CharField(choices=[('dental', 'Dental'), ('eye', 'Eye Care'), ('both', 'Both')], default='both', max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-date_added'],
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='YouTube or Vimeo URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/video_thumbnails/')),
                ('service_type', models.CharField(choices=[('dental', 'Dental'), ('eye', 'Eye Care'), ('both', 'Both')], default='both', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.gallerycategory')),
            ],
            options={
                'verbose_name': 'Video Gallery',
                'verbose_name_plural': 'Video Galleries',
                'ordering': ['order', '-date_added'],
            },
        ),
    ]
