# Generated by Django 6.0.5 on 2026-05-23 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('dental', 'Dental Care'), ('eye', 'Eye Care'), ('appointment', 'Appointments'), ('payment', 'Payments'), ('insurance', 'Insurance'), ('emergency', 'Emergency')], default='general', max_length=50)),
                ('keywords', models.CharField(blank=True, help_text='Comma separated keywords for matching', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'view_count'],
            },
        ),
        migrations.CreateModel(
            name='SymptomChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=200)),
                ('possible_conditions', models.TextField()),
                ('recommendation', models.TextField()),
                ('urgency_level', models.CharField(choices=[('low', 'Low - Can wait for regular appointment'), ('medium', 'Medium - Schedule within a week'), ('high', 'High - See doctor within 24-48 hours'), ('emergency', 'Emergency - Seek immediate care')], default='low', max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
