# Generated by Django 6.0.5 on 2026-05-25 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1 Star - Poor'), (2, '⭐⭐ 2 Stars - Fair'), (3, '⭐⭐⭐ 3 Stars - Good'), (4, '⭐⭐⭐⭐ 4 Stars - Very Good'), (5, '⭐⭐⭐⭐⭐ 5 Stars - Excellent')], default=5)),
                ('feedback_text', models.TextField()),
                ('topic', models.CharField(blank=True, help_text='e.g., Cleanliness, Staff Behavior, Treatment Quality', max_length=200, null=True)),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Show this feedback on homepage')),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to show on website')),
                ('admin_response', models.TextField(blank=True, help_text='Admin can respond to feedback', null=True)),
                ('responded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clinic Feedback',
                'verbose_name_plural': 'Clinic Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1 Star - Poor'), (2, '⭐⭐ 2 Stars - Fair'), (3, '⭐⭐⭐ 3 Stars - Good'), (4, '⭐⭐⭐⭐ 4 Stars - Very Good'), (5, '⭐⭐⭐⭐⭐ 5 Stars - Excellent')], default=5)),
                ('feedback_text', models.TextField()),
                ('treatment_received', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to show on website')),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('responded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Feedback',
                'verbose_name_plural': 'Doctor Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
