# Generated by Django 6.0.5 on 2026-05-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(default='Kathmandu, Nepal', max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(default='Kathmandu', max_length=100)),
                ('state', models.CharField(default='Bagmati Province', max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('pincode', models.CharField(default='44600', max_length=20)),
                ('phone_primary', models.CharField(default='+977 9800000000', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('emergency_phone', models.CharField(default='+977 9800000000', max_length=20)),
                ('whatsapp_number', models.CharField(default='+977 9800000000', max_length=20)),
                ('email_primary', models.EmailField(default='info@shreekrishnadental.com', max_length=254)),
                ('email_support', models.EmailField(default='support@shreekrishnadental.com', max_length=254)),
                ('email_appointments', models.EmailField(default='appointments@shreekrishnadental.com', max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('monday_friday_start', models.TimeField(default='09:00')),
                ('monday_friday_end', models.TimeField(default='20:00')),
                ('saturday_start', models.TimeField(default='10:00')),
                ('saturday_end', models.TimeField(default='17:00')),
                ('sunday_start', models.TimeField(default='10:00')),
                ('sunday_end', models.TimeField(default='17:00')),
                ('is_sunday_open', models.BooleanField(default=True)),
                ('google_maps_embed_url', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=27.7172, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=85.324, max_digits=10)),
                ('clinic_image', models.ImageField(blank=True, null=True, upload_to='clinic/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Clinic Information',
                'verbose_name_plural': 'Clinic Information',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('appointment', 'Appointment Related'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('career', 'Career Opportunity'), ('other', 'Other')], default='general', max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=50)),
                ('best_time_to_call', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('email_primary', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_support', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
