# Generated by Django 6.0.5 on 2026-05-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='bar_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='bar_address_icon',
            field=models.CharField(default='fas fa-map-marker-alt', max_length=50),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='bar_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='bar_email_icon',
            field=models.CharField(default='fas fa-envelope', max_length=50),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='bar_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='bar_hours_icon',
            field=models.CharField(default='fas fa-clock', max_length=50),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='bar_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='bar_phone_icon',
            field=models.CharField(default='fas fa-phone-alt', max_length=50),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='show_contact_bar',
            field=models.BooleanField(default=True),
        ),
    ]
