# Generated by Django 6.0.5 on 2026-05-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g., 120/80', max_length=50, null=True)),
                ('diabetes', models.BooleanField(default=False)),
                ('thyroid', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, help_text='List any allergies', null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('past_surgeries', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('last_dental_visit', models.DateField(blank=True, null=True)),
                ('dental_issues', models.TextField(blank=True, null=True)),
                ('last_eye_exam', models.DateField(blank=True, null=True)),
                ('glasses_contact_lens', models.CharField(blank=True, max_length=100, null=True)),
                ('eye_issues', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='accounts.patientprofile')),
            ],
        ),
    ]
