# Generated by Django 6.0.5 on 2026-05-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Shree Krishna Dental', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('mission_text', models.TextField(blank=True, null=True)),
                ('vision_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload about section image', null=True, upload_to='about/')),
                ('features', models.JSONField(blank=True, default=list)),
                ('years_experience', models.IntegerField(default=10)),
                ('happy_patients', models.IntegerField(default=5000)),
                ('expert_doctors', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
