# Generated by Django 6.0.5 on 2026-05-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-star', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clinic Feature',
                'verbose_name_plural': 'Clinic Features',
                'ordering': ['order'],
            },
        ),
    ]
