# Generated by Django 6.0.5 on 2026-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendance_marked_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendance_notes',
            field=models.TextField(blank=True, help_text='Notes about patient attendance', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('came', 'Came to Clinic'), ('not_came', 'Did Not Come'), ('rescheduled', 'Rescheduled')], default='pending', help_text='Did the patient come to the clinic?', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_request_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_requested',
            field=models.BooleanField(default=False),
        ),
    ]
