# Generated by Django 6.0.5 on 2026-05-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_attendance_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Suggested follow-up date', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_needed',
            field=models.BooleanField(default=False, help_text='Does patient need follow-up?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_notes',
            field=models.TextField(blank=True, help_text="Doctor's notes for follow-up", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='next_appointment_created',
            field=models.BooleanField(default=False, help_text='Has next appointment been created?'),
        ),
    ]
