# Generated by Django 6.0.5 on 2026-09-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_follow_up_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('confirmed', 'Patient Confirmed'), ('cancelled', 'Patient Cancelled')], default='sent', max_length=20)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('no_show_probability', models.FloatField(blank=True, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=200, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Appointment Reminder',
                'verbose_name_plural': 'Appointment Reminders',
                'ordering': ['-sent_at'],
            },
        ),
    ]
