# Generated by Django 6.0.5 on 2026-05-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('specialization_type', models.CharField(choices=[('dental', 'Dental Specialist'), ('eye', 'Eye Specialist')], max_length=50)),
                ('degree', models.CharField(choices=[('bds', 'BDS'), ('mds', 'MDS'), ('mbbs', 'MBBS'), ('md', 'MD'), ('ms', 'MS'), ('dm', 'DM')], max_length=50)),
                ('specialization', models.CharField(help_text='e.g., Orthodontist, Cataract Surgeon', max_length=200)),
                ('experience_years', models.IntegerField()),
                ('qualifications', models.TextField(help_text='Detailed qualifications and certifications')),
                ('expertise', models.TextField(help_text='Areas of expertise')),
                ('languages', models.CharField(help_text='e.g., English, Nepali, Hindi', max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('availability', models.CharField(help_text='e.g., Mon-Sat, 10 AM - 6 PM', max_length=200)),
                ('bio', models.TextField()),
                ('education', models.JSONField(default=list, help_text='List of education details')),
                ('awards', models.JSONField(blank=True, default=list, help_text='List of awards and achievements')),
                ('memberships', models.JSONField(blank=True, default=list, help_text='Professional memberships')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('icon_class', models.CharField(default='fas fa-user-md', max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='doctors.doctor')),
            ],
            options={
                'ordering': ['doctor', 'day', 'start_time'],
                'unique_together': {('doctor', 'day')},
            },
        ),
    ]
