# Generated by Django 6.0.5 on 2026-05-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Homepage'), ('about', 'About Us'), ('dental_services', 'Dental Services'), ('eye_services', 'Eye Care Services'), ('doctors', 'Doctors'), ('contact', 'Contact'), ('blog', 'Blog'), ('gallery', 'Gallery')], max_length=50, unique=True)),
                ('page_url', models.CharField(blank=True, help_text='Custom URL if not standard', max_length=300)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/page_og/')),
                ('schema_type', models.CharField(blank=True, max_length=100)),
                ('custom_schema', models.JSONField(blank=True, default=dict)),
                ('no_index', models.BooleanField(default=False, help_text='Add noindex meta tag')),
                ('no_follow', models.BooleanField(default=False, help_text='Add nofollow meta tag')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Shree Krishna Dental & Eye Care', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=300)),
                ('site_description', models.TextField(default='Best dental and eye care services in Kathmandu, Nepal. Expert doctors, advanced technology, affordable prices.', max_length=500)),
                ('site_keywords', models.CharField(default='dental clinic, eye care, dentist, ophthalmologist, tooth implant, cataract surgery, LASIK', max_length=500)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('business_type', models.CharField(default='MedicalClinic', max_length=100)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with Large Image')], default='summary_large_image', max_length=50)),
                ('twitter_site', models.CharField(blank=True, max_length=100)),
                ('google_verification', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=200)),
                ('bing_verification', models.CharField(blank=True, max_length=200)),
                ('yandex_verification', models.CharField(blank=True, max_length=200)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
                ('custom_header_code', models.TextField(blank=True, help_text='Custom code to add to <head> section')),
                ('custom_footer_code', models.TextField(blank=True, help_text='Custom code to add before </body>')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='sites.site')),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
