# Generated by Django 6.0.5 on 2026-05-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('service_type', models.CharField(choices=[('checkup', 'Eye Checkup'), ('cataract', 'Cataract Surgery'), ('lasik', 'LASIK'), ('retina', 'Retina Service'), ('glaucoma', 'Glaucoma'), ('contact_lens', 'Contact Lens'), ('optical', 'Optical Store'), ('vision_therapy', 'Vision Therapy')], max_length=50)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-eye', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/eyecare/')),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('faq_title', models.CharField(blank=True, max_length=300)),
                ('faq_answer', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_note', models.CharField(blank=True, max_length=200)),
                ('procedure_duration', models.CharField(blank=True, max_length=100)),
                ('recovery_time', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eye Care Service',
                'verbose_name_plural': 'Eye Care Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EyeTestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('includes', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EyeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, help_text='e.g., 15-30 minutes', max_length=100)),
                ('recovery_time', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='eyecare.eyeservice')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EyeFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='eyecare.eyeservice')),
            ],
            options={
                'ordering': ['order', 'question'],
            },
        ),
    ]
